# Generated by Django 2.2.12 on 2020-05-31 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(default=1800, help_text='Enter a publishing year', validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1800)], verbose_name='Publishing year'),
        ),
    ]
