# Generated by Django 2.2.12 on 2020-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_adaptation_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptation',
            name='link',
            field=models.CharField(help_text='Provide an IMDB link', max_length=255, verbose_name='Link'),
        ),
    ]
