# Generated by Django 2.2.12 on 2020-05-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200531_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
