# Generated by Django 2.2.12 on 2020-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200531_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_adaptation',
            field=models.BooleanField(default=False),
        ),
    ]
