# Generated by Django 2.2.12 on 2020-05-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_has_adaptation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='has_adaptation',
        ),
    ]
